import { CrawledPage, FixScriptData, FixItem, OnPageResult, IndexabilityResult } from '@/types/audit';

export function buildFixScript(
  pages: CrawledPage[], onPage: OnPageResult, indexability: IndexabilityResult,
  aiFixItems: FixItem[], faqFixItems: FixItem[]
): FixScriptData {
  const fixes: FixItem[] = [...aiFixItems, ...faqFixItems];

  for (const issue of indexability.canonicalIssues) {
    if (issue.type === 'missing' || issue.type === 'points_to_homepage') {
      fixes.push({ type: 'canonical', url: issue.url, value: issue.url });
    }
  }
  for (const noindex of indexability.noindexPages) {
    fixes.push({ type: 'noindex_removal', url: noindex.url, value: 'index,follow' });
  }

  return { script: generateJsSnippet(fixes), fixes, sitemapXml: generateSitemapXml(pages), robotsTxt: generateRobotsTxt(pages[0]?.url || '') };
}

function generateJsSnippet(fixes: FixItem[]): string {
  const byUrl: Record<string, Record<string, string>> = {};
  for (const fix of fixes) {
    if (!byUrl[fix.url]) byUrl[fix.url] = {};
    byUrl[fix.url][fix.type] = fix.value;
  }
  return `<!-- VibeSEO Fix Script — generated by vibeseo.app -->
<script>
(function(){
  var fixes=${JSON.stringify(byUrl)};
  var url=window.location.href.split('#')[0].replace(/\\/$/,'');
  var f=fixes[url]||fixes[url+'/']||{};
  if(f.meta_title&&(!document.title||document.title.length<5))document.title=f.meta_title;
  if(f.meta_description){var m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement('meta');m.name='description';document.head.appendChild(m);}if(!m.content)m.setAttribute('content',f.meta_description);}
  if(f.canonical){var c=document.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c);}try{var e=new URL(c.getAttribute('href')||'',location.href).href.replace(/\\/$/,'');if(!c.getAttribute('href')||e===location.origin+'/')c.setAttribute('href',f.canonical);}catch(e){c.setAttribute('href',f.canonical);}}
  if(f.noindex_removal){var r=document.querySelector('meta[name="robots"]');if(r&&r.getAttribute('content').toLowerCase().includes('noindex'))r.setAttribute('content','index,follow');}
  if(f.faq_schema){var s=document.querySelector('script[type="application/ld+json"]');if(!s){s=document.createElement('script');s.type='application/ld+json';s.textContent=f.faq_schema;document.head.appendChild(s);}}
})();
</script>`;
}

export function generateSitemapXml(pages: CrawledPage[]): string {
  const now = new Date().toISOString().split('T')[0];
  const urls = pages.filter(p => p.statusCode === 200).map(p => `  <url><loc>${escXml(p.url)}</loc><lastmod>${now}</lastmod><changefreq>weekly</changefreq><priority>${p.url.split('/').length <= 4 ? '0.8' : '0.6'}</priority></url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>`;
}

export function generateRobotsTxt(siteUrl: string): string {
  let origin = '';
  try { origin = new URL(siteUrl).origin; } catch { origin = siteUrl; }
  return `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /_next/\n\nSitemap: ${origin}/sitemap.xml`;
}

function escXml(s: string): string {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
